version: "3"

services:
  # Nginx
  web:
    container_name: web
    networks:
      default:
        aliases:
          - unko.local
      #redisと同じネットワークに
      app_net:
    image: nginx:1.17-perl
    command: nginx -g "daemon off; load_module /etc/nginx/modules/ngx_http_perl_module-debug.so";
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/server:/usr/share/nginx/html
      - ./dockerfiles/web/logs:/var/log/nginx
    env_file: .env
    depends_on:
      - php

  # php-fpm
  php:
    container_name: phpfpm
    build: ./dockerfiles/php
    working_dir: /usr/share/nginx/html
    ports:
      - "9000"
    volumes:
      - ./dockerfiles/php/www.conf:/etc/php-fpm.d/www.conf
      - ./src/server:/usr/share/nginx/html
      - ./dockerfiles/php/xdebug.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    env_file: .env
    networks:
      #redisと同じネットワークに
      app_net:

  # Database
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - ./dockerfiles/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./dockerfiles/mysql/conf.d:/etc/mysql/conf.d
      - ./dockerfiles/mysql/log:/var/log/mysql
    env_file: .env
    hostname: mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      #redisと同じネットワークに
      app_net:

  #redisの設定
  redis-cluster:
    image: redis:latest
    container_name: redis-cluster
    # ./docker/redis の内容を /data/conf にマウント
    volumes:
      - ./dockerfiles/redis/:/data/conf
    # コンテナが起動したら、
    # redis-serverとクラスター・レプリケーションの設定を行うshellスクリプトを実行。
    # その後、常時起動のコマンドを走らせる。
    command: bash -c "/bin/bash /data/conf/redis.sh && while true; do echo 1; sleep 1; done"
    ports:
      - 7000:7000
      - 7001:7001
      - 7002:7002
#      - 7003:7003
#      - 7004:7004
#      - 7005:7005
    #shellスクリプト内でipを使用するのでここで設定。
    networks:
      app_net:
        ipv4_address: 172.16.239.10

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1